development:
  adapter: postgresql
  encoding: unicode
  database: contact_form_development
  pool: 5
  username:
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: contact_form_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: contact_form_production
  pool: 5
  username:
  password:
